### ISSUE TITLE
Create an attractive README for this color-game repo

### ISSUE THREAD

**Issue by kanchi2438** [kanchi2438/ColorGame#1]
Do add it's preview , tech stack used (HTML 5, CSS, JavaScript, bootstrap 4) and working i.e. it generates random RGB color combination and you've to guess that color from given color palette .
Also star the repo , if you like it :)

**Comment by dunklesToast** [comment]
Thanks for merging! Unfortunately you haven't set the hacktoberfest Topic for the Repo. Could you please add this Topic? Otherwise the PR does not count :/
You can change Topics in the Code View on the settings sign on the right site

**Comment by kanchi2438** [comment]
@dunklesToast Thanks for informing , I've added the topics 👍
